In [1]:
import numpy as np

In [3]:
preliminary_contribs = np.array([3, 4, 3, 5, 0, 5, 3, 3, 3, 2, 5, 2])
num_participants = len(preliminary_contribs) 

print("Preliminary sum:", np.sum(preliminary_contribs))

Preliminary sum: 38


In [17]:
# Step 3: Define the fixed bins (ranges) for the tables
# These are the 6 average ranges from the experiment table.
bins = [
    (0.0, 0.499),
    (0.5, 1.499),
    (1.5, 2.499),
    (2.5, 3.499),
    (3.5, 4.499),
    (4.5, 5.0)
]

# Step 3.1: Input the 12 students' table values here
# Each student's table is a list of 6 integers, corresponding to the 6 bins above.
# For example, if a student wrote [0, 1, 2, 3, 3, 4], use that.
# Order them to match the preliminary_contribs order (first list for first student, etc.).
# Replace the placeholders below with the actual values from each student's table.
student_tables = [
[3, 3, 0, 5, 0, 4],  # Student 1
[1, 4, 0, 5, 1, 5],  # Student 2
[4, 3, 2, 3, 2, 2],  # Student 3
[1, 4, 2, 4, 3, 5],  # Student 4
[4, 3, 4, 5, 1, 4],  # Student 5
[5, 2, 4, 4, 0, 3],  # Student 6
[0, 1, 4, 3, 3, 3],  # Student 7
[0, 4, 1, 1, 1, 3],  # Student 8
[0, 5, 3, 5, 5, 2],  # Student 9
[4, 4, 3, 5, 0, 0],  # Student 10
[5, 5, 5, 4, 4, 1],  # Student 11
[0, 3, 1, 2, 0, 5]   # Student 12
]

# Ensure there are 12 tables
assert len(student_tables) == num_participants, "Must provide exactly 12 student tables"

In [19]:
# Step 4: Define the function to get bin index for a given avg_others
def get_bin_index(avg_others):
    for idx, (low, high) in enumerate(bins):
        if low <= avg_others <= high:  # Use <= for high to include 5.0
            return idx
    raise ValueError(f"Average {avg_others} out of bounds")

# Step 5: Simulate the 10 rounds
# Start with current_contribs = preliminary
current_contribs = preliminary_contribs.copy()

# We'll store all rounds in a list of arrays for tracking (optional, but helpful)
all_rounds = [current_contribs.copy()]  # Round 1 (preliminary)

for round_num in range(1, 11):  # 10 iterations (rounds 2 to 11)
    total = np.sum(current_contribs)
    new_contribs = np.zeros(num_participants, dtype=int)
    
    for i in range(num_participants):
        avg_others = (total - current_contribs[i]) / (num_participants - 1)
        bin_idx = get_bin_index(avg_others)
        new_contribs[i] = student_tables[i][bin_idx]
    
    current_contribs = new_contribs
    all_rounds.append(current_contribs.copy())
    
    print(f"After round {round_num + 1}: sum = {np.sum(current_contribs)}")
    print(current_contribs)

# Final contributions are in current_contribs (after 10 rounds)

After round 2: sum = 46
[5 5 3 4 5 4 3 1 5 5 4 2]
After round 3: sum = 20
[0 1 2 3 1 0 3 1 5 0 4 0]
After round 4: sum = 31
[0 0 2 2 4 4 4 1 5 3 5 1]
After round 5: sum = 45
[5 5 3 4 4 4 4 1 3 5 5 2]
After round 6: sum = 20
[0 1 2 3 1 0 3 1 5 0 4 0]
After round 7: sum = 31
[0 0 2 2 4 4 4 1 5 3 5 1]
After round 8: sum = 45
[5 5 3 4 4 4 4 1 3 5 5 2]
After round 9: sum = 20
[0 1 2 3 1 0 3 1 5 0 4 0]
After round 10: sum = 31
[0 0 2 2 4 4 4 1 5 3 5 1]
After round 11: sum = 45
[5 5 3 4 4 4 4 1 3 5 5 2]


In [21]:
# Step 6: Calculate final payoffs
# Final pot = sum of final contributions
final_pot = np.sum(current_contribs)

# Doubled pot
doubled_pot = final_pot * 2

# Share per participant
share = doubled_pot / num_participants

# Individual payoffs: (5 - final_contrib) + share for each
payoffs = (5 - current_contribs) + share

# Bonus per participant: payoff / 40
bonuses = payoffs / 40

# Print results
print("Final pot:", final_pot)
print("Doubled pot:", doubled_pot)
print("Share per participant:", share)
print("Payoffs:", payoffs)
print("Bonuses:", bonuses)

Final pot: 45
Doubled pot: 90
Share per participant: 7.5
Payoffs: [ 7.5  7.5  9.5  8.5  8.5  8.5  8.5 11.5  9.5  7.5  7.5 10.5]
Bonuses: [0.1875 0.1875 0.2375 0.2125 0.2125 0.2125 0.2125 0.2875 0.2375 0.1875
 0.1875 0.2625]
